title: EuRuKo 2017 - Budapest
description: >
  Euruko is an annual Ruby Conference in Europe.
  Visit Budapest, Hungary on September 29-30, 2017.
baseurl: ""
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-redirect-from
